embedding_model: "sentence-transformers/all-MiniLM-L6-v2"
gguf_model_path: "model/tinyllama-1.1b-chat-v1.0.Q3_K_S.gguf"
storage_path: "storage"

chunk_size: 1024
embedding_dimension: 384

max_new_tokens: 1024
top_k: 2
top_p: 0.8
temperature: 0.6
context_window: 3900

data_path: "data"

log_level: "INFO"