name: Check and packaging

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  formatting-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install black
        run: pip install black

      - name: Run black
        run: black .

  packaging:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install briefcase
        run: pip install briefcase==0.3.19

      - name: Perform packaging
        run: |
          briefcase package

      - name: Upload package
        uses: actions/upload-artifact@v7
        with:
          name: tachyonot
          path: |
            dist/*
          if-no-files-found: error

